require('plugins')
require('settings')
require('mappings')
require('nv-lsp')
require('nv-compe')
require('nv-lspkind')
require('nv-lightbulb')
require('nv-telescope')
require('nv-onebuddy')

vim.cmd('source ~/.config/nvim/vimscript/functions.vim')